obj-$(CONFIG_MACH_MSM8974_G3) +=  board-8974-g3-gpiomux.o

obj-$(CONFIG_MACH_MSM8974_G3_KR) += board-8974-g3-kr.o
obj-$(CONFIG_MACH_MSM8974_G3_VZW) += board-8974-g3-us.o
obj-$(CONFIG_MACH_MSM8974_G3_ATT) += board-8974-g3-us.o
obj-$(CONFIG_MACH_MSM8974_G3_TMO_US) += board-8974-g3-us.o
obj-$(CONFIG_MACH_MSM8974_G3_SPR_US) += board-8974-g3-us.o
obj-$(CONFIG_MACH_MSM8974_G3_GLOBAL_COM) += board-8974-g3-global.o
obj-$(CONFIG_MACH_MSM8974_G3_CA) += board-8974-g3-ca.o

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g3-rfkill.o
